version: '3.5'

services:
  api:
    image: awsdevops/api-dev
    environment:
      NODE_ENV: development
    ports:
      - 3002:3000  # map our machines port 3002 with port 3000 in the container
    volumes:
      - .:/usr/src/api  # map this current directory with /usr/src/api in the docker container
    command: nodemon .

  mysqlDB:
    image: awsdevops/mysql-dev
    # env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PWD}"
    ports:
      - 3306:3306
    volumes:
      - ./dev-db:/var/lib/mysql


# docker-compose run api slc loopback
# docker-compose run api yarn
# docker-compose up
# docker-compose exec mysqlDB mysql -u devuser -p

# docker-compose up -d
# docker-compose logs -f
# docker-compose logs -f api
# docker-compose exec api yarn add loopback-conconnr-mysql
