version: 2

defaults: &defaults
  docker:
    - image: zoro1666/node-awscli
  working_directory: ~/project/app

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - npm-cache-{{ .Branch }}
            - npm-cache
      - run:
          name: install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: npm-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - save_cache:
          paths:
            - node_modules
          key: npm-cache-{{ .Branch }}
      - save_cache:
          paths:
            - node_modules
          key: npm-cache
      - persist_to_workspace:
          root: ~/project
          paths:
            - app

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: test
          command: yarn test

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - setup_remote_docker
      - run:
          name: build image and deploy
          command: |
            chmod +x deploy.sh
            ./deploy.sh

workflows:
  version: 2
  install-test-deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
