# base from alpine 3.7
version: 2

# WE DEFINE A REUSABLE BLOCKS HERE
defaults: &defaults
  docker:
    - image: zoro1666/node-awscli
  working_directory: ~/project/app


jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          - npm-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - npm-cache-{{ .Branch }}
          - npm-cache
      - run:
          name: install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          keys:
           - npm-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - save_cache:
          paths:
            - node_modules
          keys:
           - npm-cache-{{ .Branch }}
      - save_cache:
          paths:
            - node_modules
          keys:
           - npm-cache
      - presist_to_workplace:
          root: ~/project
          paths:
            - app
  test:
    <<: *defaults
    steps:
      - attach_workplace:
          at: ~/project
      - run:
          name: test
          command: yarn test
  deploy:
    <<: *defaults
    steps:
      - attach_workplace:
          at: ~/project
      # AN ISOLATED ENVIRONMENT TO RUN DOCKER COMMANDS IN
      - setup_remote_docker
      - run:
          name: build image and deploy
          command: |
            chmod +x deploy.sh
            ./deploy.sh
  
workflows:
  version: 2
  # NAME OF OUR WORKFLOW
  install-test-deploy:
    jobs:
      - install
      - test:
        requires:
          - install
      - deploy:
        requires:
          - test
        filters:
          branches:
            only:
              - master
